version: "3.8"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/code
      - ./alembic/versions:/code/alembic/versions
      - ./logs:/code/logs
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:5432

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  postgres_data:
  logs:

networks:
  default:
    driver: bridge
